// Generated by CoffeeScript 1.9.3
var Contact, CozyAdapter, DataPoint, americano, async, clearance, e,
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty,
  indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

clearance = require('./index');

async = require('async');

americano = require('cozy-db-pouchdb');

DataPoint = (function(superClass) {
  extend(DataPoint, superClass);

  function DataPoint() {
    return DataPoint.__super__.constructor.apply(this, arguments);
  }

  DataPoint.schema = {
    name: String,
    value: String,
    type: String
  };

  return DataPoint;

})(cozydb.Model);

Contact = americano.getModel('Contact', {
  fn: String,
  n: String,
  _attachments: Object,
  datapoints: [DataPoint]
});

CozyAdapter = (function() {
  try {
    return require('americano-cozy-pouchdb/node_modules/jugglingdb-pouchdb-adapter');
  } catch (_error) {
    e = _error;
    return require('jugglingdb-pouchdb-adapter');
  }
})();

module.exports = function(options) {
  var mailSubject, mailTemplate, out, sendMail;
  out = {};
  mailSubject = options.mailSubject;
  mailTemplate = options.mailTemplate;
  sendMail = function(doc, key, cb) {
    var rule;
    rule = doc.clearance.filter(function(rule) {
      return rule.key === key;
    })[0];
    return doc.getPublicURL((function(_this) {
      return function(err, url) {
        var emailOptions;
        if (err) {
          return cb(err);
        }
        url += '?key=' + rule.key;
        emailOptions = {
          doc: doc,
          url: url,
          rule: rule
        };
        return async.parallel([
          function(cb) {
            return mailSubject(emailOptions, cb);
          }, function(cb) {
            return mailTemplate(emailOptions, cb);
          }
        ], function(err, results) {
          var emailInfo, htmlContent, subject;
          subject = results[0], htmlContent = results[1];
          emailInfo = {
            to: rule.email,
            subject: subject,
            content: url,
            html: htmlContent
          };
          return CozyAdapter.sendMailFromUser(emailInfo, cb);
        });
      };
    })(this));
  };
  out.change = function(req, res, next) {
    clearance = req.body.clearance;
    return req.doc.updateAttributes({
      clearance: clearance
    }, function(err) {
      if (err) {
        return next(err);
      }
      return res.send(req.doc);
    });
  };
  out.sendAll = function(req, res, next) {
    var sent, toSend;
    toSend = req.body;
    sent = [];
    return async.each(toSend, function(rule, cb) {
      sent.push(rule.key);
      return sendMail(req.doc, rule.key, cb);
    }, function(err) {
      var newClearance;
      if (err) {
        return next(err);
      }
      newClearance = req.doc.clearance.map(function(rule) {
        var ref;
        if (ref = rule.key, indexOf.call(sent, ref) >= 0) {
          rule.sent = true;
        }
        return rule;
      });
      return req.doc.updateAttributes({
        clearance: newClearance
      }, function(err) {
        if (err) {
          return next(err);
        }
        return res.send(req.doc);
      });
    });
  };
  out.getEmailsFromContactFields = function(contact) {
    var emails, ref;
    emails = (ref = contact.datapoints) != null ? ref.filter(function(dp) {
      return dp.name === 'email';
    }) : void 0;
    emails = emails.map(function(dp) {
      return dp.value;
    });
    return emails;
  };
  out.getContactFullName = function(contact) {
    var ref;
    return contact.fn || ((ref = contact.n) != null ? ref.split(';').slice(0, 2).join(' ') : void 0);
  };
  out.contactList = function(req, res, next) {
    return Contact.request('all', function(err, contacts) {
      if (err) {
        return next(err);
      }
      return res.send(contacts.map(function(contact) {
        var emails, name, ref, simple;
        name = out.getContactFullName(contact);
        emails = out.getEmailsFromContactFields(contact);
        return simple = {
          id: contact.id,
          hasPicture: ((ref = contact._attachments) != null ? ref.picture : void 0) != null,
          name: name || '?',
          emails: emails || []
        };
      }));
    });
  };
  out.contactPicture = function(req, res, next) {
    return Contact.find(req.params.contactid, function(err, contact) {
      var ref, stream;
      if (err) {
        return next(err);
      }
      if (!((ref = contact._attachments) != null ? ref.picture : void 0)) {
        err = new Error('not found');
        err.status = 404;
        return next(err);
      }
      stream = contact.getFile('picture', function(err) {
        if (err) {
          return res.error(500, "File fetching failed.", err);
        }
      });
      return stream.pipe(res);
    });
  };
  return out;
};
